service: add-sg-rule
provider:
  name: aws
  runtime: python3.6
  stage: prd
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:RevokeSecurityGroupIngress"
        - "ec2:AuthorizeSecurityGroupEgress"
        - "ec2:AuthorizeSecurityGroupIngress"
        - "ec2:UpdateSecurityGroupRuleDescriptionsEgress"
        - "ec2:DescribeSecurityGroupReferences"
        - "ec2:RevokeSecurityGroupEgress"
        - "ec2:DescribeSecurityGroups"
        - "ec2:UpdateSecurityGroupRuleDescriptionsIngress"
        - "ec2:DescribeStaleSecurityGroups"
      Resource:
        - "*"

functions:
  add-sg-rule:
    handler: handler.lambda_handler
    events:
      - schedule: ${env:SCHEDULE}
    environment:
      SGID: ${env:SGID}
